spring:
  application:
    name: ms-account
  messages:
    basename: i18n/messages
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/ced
    username: root
    password: Buster
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update